# Generated by Django 4.1.3 on 2022-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_email',
            field=models.CharField(max_length=100),
        ),
    ]
