# Generated by Django 4.1.3 on 2022-12-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_seller_seller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
